import express from 'express';
import exampleRoutes from '../modules/example/example.routes.js';
import roleRoutes from '../modules/role/role.routes.js';
import userRoutes from '../modules/user/user.routes.js';
import userProfileRoutes from '../modules/userProfile/userProfile.routes.js';
import communityCategoryRoutes from '../modules/communityCategory/communityCategory.routes.js';
import communityRoutes from '../modules/community/community.routes.js';
import communityMemberRoutes from '../modules/communityMember/communityMember.routes.js';
import businessCategoryRoutes from '../modules/business_category/business_category.routes.js';
import businessProfileRoutes from '../modules/business_profile/business_profile.routes.js';
import businessImageRoutes from '../modules/business_image/business_image.routes.js';
import businessOfferRoutes from '../modules/business_offer/business_offer.routes.js';
import businessReviewRoutes from '../modules/business_review/business_review.routes.js';
import serviceCategoryRoutes from '../modules/service_category/service_category.routes.js';
import serviceProviderProfileRoutes from '../modules/service_provider_profile/service_provider_profile.routes.js';
import serviceListingRoutes from '../modules/service_listing/service_listing.routes.js';
import serviceBookingRoutes from '../modules/service_booking/service_booking.routes.js';
import serviceReviewRoutes from '../modules/service_review/service_review.routes.js';
import societyProfileRoutes from '../modules/society_profile/society_profile.routes.js';
import societyMemberRoutes from '../modules/society_member/society_member.routes.js';
import societyFacilityRoutes from '../modules/society_facility/society_facility.routes.js';
import societyAnnouncementRoutes from '../modules/society_announcement/society_announcement.routes.js';
import societyComplaintRoutes from '../modules/society_complaint/society_complaint.routes.js';
import societyVisitorRoutes from '../modules/society_visitor/society_visitor.routes.js';
import societyParkingRoutes from '../modules/society_parking/society_parking.routes.js';
import societyPollRoutes from '../modules/society_poll/society_poll.routes.js';
import mediaFileRoutes from '../modules/media_file/media_file.routes.js';
import postRoutes from '../modules/post/post.routes.js';
import postLikeRoutes from '../modules/post_like/post_like.routes.js';
import postCommentRoutes from '../modules/post_comment/post_comment.routes.js';
import postShareRoutes from '../modules/post_share/post_share.routes.js';
import savedPostRoutes from '../modules/saved_post/saved_post.routes.js';
import eventRoutes from '../modules/event/event.routes.js';
import eventCategoryRoutes from '../modules/event_category/event_category.routes.js';
import eventParticipantRoutes from '../modules/event_participant/event_participant.routes.js';
import followRoutes from '../modules/follow/follow.routes.js';
import chatRoutes from '../modules/chat/chat.routes.js';
import chatParticipantRoutes from '../modules/chat_participant/chat_participant.routes.js';
import messageRoutes from '../modules/message/message.routes.js';
import reportRoutes from '../modules/report/report.routes.js';
import notificationRoutes from '../modules/notification/notification.routes.js';
import adminDashboardRoutes from '../modules/admin_dashboard/admin_dashboard.routes.js';
import adBannerRoutes from '../modules/ad_banner/ad_banner.routes.js';
import adCampaignRoutes from '../modules/ad_campaign/ad_campaign.routes.js';
import adSponsoredRoutes from '../modules/ad_sponsored/ad_sponsored.routes.js';
import analyticsRoutes from '../modules/analytics/analytics.routes.js';
import feedRoutes from '../modules/feed/feed.routes.js';
import profileRoutes from '../modules/profile/profile.routes.js';
import authRoutes from '../modules/auth/auth.routes.js';
import deviceRoutes from '../modules/user_devices/user_device.routes.js';
import { generalApiLimiter } from '../middleware/rateLimit.middleware.js';

const router = express.Router();

// Shared Redis-backed general API limiter (skips /health)
router.use(generalApiLimiter);

// Mount example module routes
router.use('/example', exampleRoutes);
router.use('/role', roleRoutes);
router.use('/user', userRoutes);
router.use('/user-profile', userProfileRoutes);
router.use('/profile', profileRoutes);
router.use('/auth', authRoutes);
router.use('/device', deviceRoutes);
router.use('/feed', feedRoutes);
router.use('/community-category', communityCategoryRoutes);
router.use('/community', communityRoutes);
router.use('/community-member', communityMemberRoutes);
router.use('/business-category', businessCategoryRoutes);
router.use('/business-profile', businessProfileRoutes);
router.use('/business-image', businessImageRoutes);
router.use('/business-offer', businessOfferRoutes);
router.use('/business-review', businessReviewRoutes);
router.use('/service-category', serviceCategoryRoutes);
router.use('/service-provider-profile', serviceProviderProfileRoutes);
router.use('/service-listing', serviceListingRoutes);
router.use('/service-booking', serviceBookingRoutes);
router.use('/service-review', serviceReviewRoutes);
router.use('/society-profile', societyProfileRoutes);
router.use('/society-member', societyMemberRoutes);
router.use('/society-facility', societyFacilityRoutes);
router.use('/society-announcement', societyAnnouncementRoutes);
router.use('/society-complaint', societyComplaintRoutes);
router.use('/society-visitor', societyVisitorRoutes);
router.use('/society-parking', societyParkingRoutes);
router.use('/society-poll', societyPollRoutes);
router.use('/media-file', mediaFileRoutes);
router.use('/post', postRoutes);
router.use('/post-like', postLikeRoutes);
router.use('/post-comment', postCommentRoutes);
router.use('/post-share', postShareRoutes);
router.use('/saved-post', savedPostRoutes);
router.use('/event', eventRoutes);
router.use('/event-category', eventCategoryRoutes);
router.use('/event-participant', eventParticipantRoutes);
router.use('/follow', followRoutes);
router.use('/chat', chatRoutes);
router.use('/chat-participant', chatParticipantRoutes);
router.use('/message', messageRoutes);
router.use('/report', reportRoutes);
router.use('/notification', notificationRoutes);
router.use('/admin-dashboard', adminDashboardRoutes);
router.use('/ad-banner', adBannerRoutes);
router.use('/ad-campaign', adCampaignRoutes);
router.use('/ad-sponsored', adSponsoredRoutes);
router.use('/analytics', analyticsRoutes);

// Health check route
router.get('/health', (req, res) => {
  res.status(200).json({ success: true, message: 'Server is healthy' });
});

export default router;
